spring:
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:/Users/aleksandrborkan/Downloads/loyality_cms/src/main/resources/db_save/db_loyality_cms
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update